# kg.sh - Knowledge Graph Stack Module (Neo4j)

generate_kg_stack() {
  local service_name="kg"
  local kg_builder_dir="./services/kg/llm-graph-builder"
  
  # Clone the Neo4j LLM Graph Builder repo if missing
  if [[ ! -d "$kg_builder_dir" ]]; then
    echo "Cloning Neo4j LLM Graph Builder source..." >&2
    mkdir -p "$(dirname "$kg_builder_dir")"
    git clone https://github.com/neo4j-labs/llm-graph-builder.git "$kg_builder_dir" >&2
  fi

  # Construct OpenRouter config if key is present
  local or_config=""
  if [[ -n "${OPENROUTER_API_KEY:-}" ]]; then
    local or_model="${OPENROUTER_MODEL_TXT:-google/gemini-flash-1.5}"
    local or_base="${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}"
    or_config="${or_model},${or_base},${OPENROUTER_API_KEY},v1"
  fi

  # Generate Local .env files for manual fine-tuning
  mkdir -p "$kg_builder_dir/backend" "$kg_builder_dir/frontend"
  
  # Backend .env
  cat > "$kg_builder_dir/backend/.env" <<BACKEND_ENV
# KG Builder Backend Configuration
# Generated by nself - Manual edits will persist until next 'nself build --force'
NEO4J_URI=bolt://kg-neo4j:7687
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=${NSELF_ADMIN_PASSWORD:-${POSTGRES_PASSWORD:-aiopassword}}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
GOOGLE_API_KEY=${GOOGLE_API_KEY:-}

# Additional Model Configurations (Programmatic Bridge)
LLM_MODEL_CONFIG_openrouter="${or_config}"

# Extraction & Tuning Parameters
EFFECTIVE_SEARCH_RATIO=${EFFECTIVE_SEARCH_RATIO:-0.5}
DUPLICATE_SCORE_VALUE=${DUPLICATE_SCORE_VALUE:-0.8}
DUPLICATE_TEXT_DISTANCE=${DUPLICATE_TEXT_DISTANCE:-0.1}
BACKEND_ENV

  # Frontend .env
  cat > "$kg_builder_dir/frontend/.env" <<FRONTEND_ENV
# KG Builder Frontend Configuration
VITE_BACKEND_API_URL=https://${KG_ROUTE:-kg}.${BASE_DOMAIN}/api
VITE_LLM_MODELS_PROD=openai_gpt_5_mini,openai_gpt_5.2,diffbot,gemini_2.5_flash,gemini_2.5_pro,groq_llama3.1_8b,anthropic_claude_4.5_sonnet,anthropic_claude_4.5_haiku,llama4_maverick,openrouter
VITE_CHAT_MODES=vector,graph_vector,graph,fulltext,entity_vector,global_vector
VITE_ENV=PROD
VITE_AUTH_TYPE=none
VITE_SKIP_AUTH=true
FRONTEND_ENV

  # Patch the Dockerfile to increase network timeout for unstable connections
  if [[ -f "$kg_builder_dir/frontend/Dockerfile" ]]; then
    if ! grep -q "network-timeout" "$kg_builder_dir/frontend/Dockerfile"; then
       echo "Patching KG Builder Dockerfile for network stability..." >&2
       sed -i 's/yarn install/yarn install --network-timeout 1000000/' "$kg_builder_dir/frontend/Dockerfile"
    fi
    # Force VITE_AUTH_TYPE=none and declare ARGs to ensure they are available during 'yarn build'
    if ! grep -q "VITE_AUTH_TYPE" "$kg_builder_dir/frontend/Dockerfile"; then
       echo "Patching KG Builder Dockerfile to declare build args and disable SSO..." >&2
       # We inject the ARGs right after the FROM or at the beginning of the build stage
       sed -i '/yarn build/i ARG VITE_AUTH_TYPE=none\nARG VITE_SKIP_AUTH=true\nARG VITE_BACKEND_API_URL\nARG VITE_LLM_MODELS_PROD\nARG VITE_CHAT_MODES\nARG VITE_ENV' "$kg_builder_dir/frontend/Dockerfile"
    fi

    # Aggressive Frontend Patch: Trick the UI into thinking keys are configured when skipping auth
    if [[ -f "$kg_builder_dir/frontend/index.html" ]]; then
       if ! grep -q "skip-auth-patch" "$kg_builder_dir/frontend/index.html"; then
          echo "Patching KG Builder index.html to unlock models in bypass mode..." >&2
          sed -i '/<head>/a \    <script id="skip-auth-patch">\n      if ("%VITE_SKIP_AUTH%" === "true" || true) {\n        localStorage.setItem("openai_api_key", "internal");\n        localStorage.setItem("anthropic_api_key", "internal");\n        localStorage.setItem("gemini_api_key", "internal");\n        localStorage.setItem("groq_api_key", "internal");\n      }\n    </script>' "$kg_builder_dir/frontend/index.html"
          # Replace the placeholder with actual build-time value if needed (or just leave it true for bypass)
       fi
    fi
  fi

  cat <<EOF

  # Knowledge Graph Stack
  kg-neo4j:
    image: neo4j:5.26
    container_name: ${PROJECT_NAME}_kg_neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/${NSELF_ADMIN_PASSWORD:-${POSTGRES_PASSWORD:-aiopassword}}
      NEO4J_server_memory_pagecache_size: 1G
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_export_file_enabled: 'true'
    volumes:
      - kg_neo4j_data:/data
      - kg_neo4j_logs:/logs
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474/browser/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  kg-builder-backend:
    build:
      context: ${kg_builder_dir}/backend
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}_kg_builder_backend:latest
    pull_policy: build
    container_name: ${PROJECT_NAME}_kg_builder_backend
    restart: unless-stopped
    env_file:
      - ${kg_builder_dir}/backend/.env
    # environment:
    #   MODEL: ${KG_EXTRACTOR_MODEL:-anthropic/claude-sonnet-4.5}
    depends_on:
      kg-neo4j:
        condition: service_healthy
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 5

  kg-builder-frontend:
    build:
      context: ${kg_builder_dir}/frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_API_URL=https://${KG_ROUTE:-kg}.${BASE_DOMAIN}/api
        - VITE_LLM_MODELS_PROD=openai_gpt_5_mini,openai_gpt_5.2,diffbot,gemini_2.5_flash,gemini_2.5_pro,groq_llama3.1_8b,anthropic_claude_4.5_sonnet,anthropic_claude_4.5_haiku,llama4_maverick,openrouter
        - VITE_CHAT_MODES=vector,graph_vector,graph,fulltext,entity_vector,global_vector
        - VITE_ENV=PROD
        - VITE_AUTH_TYPE=none
        - VITE_SKIP_AUTH=true
    image: ${PROJECT_NAME}_kg_builder_frontend:latest
    pull_policy: build
    container_name: ${PROJECT_NAME}_kg_builder_frontend
    restart: unless-stopped
    env_file:
      - ${kg_builder_dir}/frontend/.env
    depends_on:
      - kg-builder-backend
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5


EOF
}

export -f generate_kg_stack
